% Auto-generated by Sensor Fusion & Trajectory Engine

time_vector = [0.0; 0.5; 1.0; 1.5; 2.0; 2.5; 3.0];
steer_vector = [0.0; 0.0; 0.0; 0.0; -0.0; -0.0; -0.0]; % radians
accel_vector = [-5.0; -5.0; -5.0; -5.0; 0.0; 0.0; 0.0]; % m/s^2

% Create timeseries objects for Simulink FromWorkspace blocks
SteeringInput = timeseries(steer_vector, time_vector);
AccelerationInput = timeseries(accel_vector, time_vector);

% Combine into a Simulink Dataset or timetable
ControlTimetable = timetable(seconds(time_vector), steer_vector, accel_vector, ...
    'VariableNames', {'SteeringAngle', 'Acceleration'});
